### ISSUE TITLE
Add ability to configure Agent Usage (EXCLUSIVE/NORMAL) as variable

### ISSUE THREAD

**Issue by vystrela** [lean-delivery/ansible-role-jenkins-slave#14]
##### SUMMARY

When configuring a node, a playbook should be able to configure the node's "usage" as either "Use this node as much as possible" (NORMAL) or "Only build jobs with label expressions matching this node" (EXCLUSIVE).

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

Install slave jenkins agent

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /home/bens/workspace/infra-playbooks/ansible.cfg
  configured module search path = [u'/home/bens/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Jul  9 2019, 16:51:35) [GCC 7.4.0]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
ANSIBLE_PIPELINING(env: ANSIBLE_PIPELINING) = True
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
- name: "Install jenkins-slave on remote hosts using default 'Username with password' credentials, and configuring the node for builds matching labels only"
  hosts: slave

  vars:
    master_host: master.example.com
    slave_mode_exclusive: true

  roles:
    - role: lean_delivery.jenkins_slave

- name: "Install jenkins-slave on remote hosts using default 'Username with password' credentials, and configuring the node for all builds"
  hosts: slave

  vars:
    master_host: master.example.com
    slave_mode_exclusive: false

  roles:
    - role: lean_delivery.jenkins_slave
```

##### EXPECTED RESULTS

- In the first case, the node is configured, and will only build jobs with label expressions matching this node (by default, 'linux')
![image](https://user-images.githubusercontent.com/7136138/65561546-2de36600-df86-11e9-9371-e42f22f8ffe1.png)

- In the second case, the node is configured as being used as much as possible
![image](https://user-images.githubusercontent.com/7136138/65561499-055b6c00-df86-11e9-8590-7e582d0c7e61.png)

##### ACTUAL RESULTS

Regardless of variable value, all nodes are configured as being used as much as possible.

```
TASK [lean_delivery.jenkins_slave : Install slave jenkins agent] **************
ok: [slave]
```
