### ISSUE TITLE
Installing slave agent insufficiently documented

### ISSUE THREAD

**Issue by hasufell** [lean-delivery/ansible-role-jenkins-slave#28]
```
TASK [lean_delivery.jenkins_slave : Install slave jenkins agent] ***********************************************************************
fatal: [test]: FAILED! => {"changed": false, "msg": "HTTP error 401 HTTP Error 401: Invalid password/token for user: ********", "output": ""}
```

Configuration is:

```
    - name: Install jenkins slave
      become: yes
      import_role:
        name: lean_delivery.jenkins_slave
      vars:
        master_host: xxx.com
        master_port: 80
        master_url: https://xxx.com
        slave_linux_home: /home/build
        slave_linux_jenkins_cred_id: xxx-id
        slave_linux_jenkins_username: build
        slave_linux_user_group: build
        slave_linux_jenkins_public_key: "xxx"
```

The jenkins master uses google oauth for authentication. I'm not sure what kind of configuration this ansible role expects. The jar files are perfectly accessible via wget.
