### ISSUE TITLE
After Linux VM reboot the jenkins slave is not running

### ISSUE THREAD

**Issue by alwaysharsha** [lean-delivery/ansible-role-jenkins-slave#29]
##### SUMMARY

After the installation of Jenkins slave, when we reboot the machine the slave service is not running on Linux VM.

Is there a command to atleast start the Jenkins slave service on linux machine?

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible-role-jenkins-slave

##### ANSIBLE VERSION

ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/svc_engbuild/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
```

```

##### OS / ENVIRONMENT

Ubuntu 18
##### STEPS TO REPRODUCE

```yaml
  tasks:
  - name: Install jre
    package:
      name: default-jre
      state: present
      update_cache: yes
    become: yes

  - include_role:
      name: "roles_galaxy/lean_delivery.jenkins_slave"
```
After rebooting the machine the jenkins service is not running.

##### EXPECTED RESULTS

Jenkins service should be running after reboot
##### ACTUAL RESULTS

```

```
