### ISSUE TITLE
Windows Server 2019 Install slave jenkins agent failing

### ISSUE THREAD

**Issue by unglaublicherdude** [lean-delivery/ansible-role-jenkins-slave#32]
##### SUMMARY
Task: lean_delivery.jenkins_slave : Install slave jenkins agent
Is failing on a Windows Server 2019 Server. Any Ideas? I already tried creating a completely new temp-directory

##### ISSUE TYPE
 - Bug Report / Question

##### ANSIBLE VERSION

```
ansible 2.9.0
  config file = None
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

##### OS / ENVIRONMENT

Running Ansible on
```
Description:    Ubuntu 18.04.4 LTS
```

Running against Windows Server 2019 with SSH-2.0-OpenSSH_for_Windows_7.7

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  pre_tasks:
    - name: download xxx ca certificate
      win_get_url:
        url: https://artifactory.xxx.de/pt-ata-generic/GaiaDockerImage/xxx.crt
        dest: 'C:\Users\{{ansible_ssh_user}}\AppData\Local\Temp\xxx.crt'
    - name: install cert
      win_certificate_store:
        path: 'C:\Users\{{ansible_ssh_user}}\AppData\Local\Temp\xxx.crt'
        state: present
        store_name: AuthRoot # The X.509 certificate store for third-party certificate authorities (CAs)

  roles:
    - name: lean_delivery.jenkins_slave
      vars:
        master_username: admin
        master_password: somesecret
        master_host: jenkins.seclab-apphost-xxx-dev.xxx.de
        master_port: 443
        slave_agent_name: windws_build_server
        slave_executors_num: 2
        slave_mode_exclusive: true
        slave_windows_labels: 
          - dnsclientwindows
        master_url: https://jenkins.seclab-apphost-xxx-dev.xxx.de/
```

Group Vars:
```yaml
---
ansible_connection: ssh
ansible_shell_type: powershell
ansible_ssh_user: Administrator
ansible_password: somesecret
```

##### EXPECTED RESULTS

A jenkins agent to be installed.

##### ACTUAL RESULTS

```
TASK [lean_delivery.jenkins_slave : Install slave jenkins agent] *************************************************
fatal: [dnscloud-integration-win2019.ptata.xxx.de]: FAILED! => {"msg": "failed to resolve remote temporary directory from ansible-tmp-1584621901.9740524-168549963248385: `PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAkAHQAbQBwAF8AcABhAHQAaAAgAD0AIABbAFMAeQBzAHQAZQBtAC4ARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AEUAeABwAGEAbgBkAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABWAGEAcgBpAGEAYgBsAGUAcwAoACcAQwA6AFwAVQBzAGUAcgBzAFwAQQBkAG0AaQBuAGkAcwB0AHIAYQB0AG8AcgBcAHQAZQBtAHAAJwApAAoAJAB0AG0AcAAgAD0AIABOAGUAdwAtAEkAdABlAG0AIAAtAFQAeQBwAGUAIABEAGkAcgBlAGMAdABvAHIAeQAgAC0AUABhAHQAaAAgACQAdABtAHAAXwBwAGEAdABoACAALQBOAGEAbQBlACAAJwBhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADUAOAA0ADYAMgAxADkAMAAxAC4AOQA3ADQAMAA1ADIANAAtADEANgA4ADUANAA5ADkANgAzADIANAA4ADMAOAA1ACcACgBXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgAC0ASQBuAHAAdQB0AE8AYgBqAGUAYwB0ACAAJAB0AG0AcAAuAEYAdQBsAGwATgBhAG0AZQAKAEkAZgAgACgALQBuAG8AdAAgACQAPwApACAAewAgAEkAZgAgACgARwBlAHQALQBWAGEAcgBpAGEAYgBsAGUAIABMAEEAUwBUAEUAWABJAFQAQwBPAEQARQAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQApACAAewAgAGUAeABpAHQAIAAkAEwAQQBTAFQARQBYAEkAVABDAE8ARABFACAAfQAgAEUAbABzAGUAIAB7ACAAZQB4AGkAdAAgADEAIAB9ACAAfQA=` returned empty string"}
```
