### ISSUE TITLE
RHEL 8 install fails due to selinux config

### ISSUE THREAD

**Issue by wwtbushnelo** [lean-delivery/ansible-role-jenkins-slave#43]
##### SUMMARY

Using this role to setup an agent on RHEL 8 fails to setup the selinux support files.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.6/site-packages/pyateos/modules', '/usr/local/lib/python3.6/site-packages/git_acp/modules', '/usr/local/lib/python3.6/site-packages/napalm_ansible/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/napalm_ansible/plugins/action']
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ansible/plugins/filter']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/pyateos/modules', '/usr/local/lib/python3.6/site->
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
DUPLICATE_YAML_DICT_KEY(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Running on RHEL  8.3.1-5
Configuring RHEL  8.3.1-5

##### STEPS TO REPRODUCE

Run the playbook with target_vm set to the vm to configure and appropriate credentials.

```yaml
- name: Start Jenkins
  hosts: "{{ target_vm }}"
  become: true
  roles:
    - role: lean_delivery.java
      transport: repositories
      java_major_version: 8
    - role: lean_delivery.jenkins_slave
  vars:
    master_host: "{{ jenkins_master }}"
    master_username: "{{ jenkins_master_user }}"
    master_password: "{{ jenkins_master_password }}"
    slave_linux_jenkins_cred_id: agent_id
    slave_linux_jenkins_username: "{{ agent_user }}"
    slave_linux_jenkins_password: "{{ agent_password }}"
    slave_agent_name: linux_agent
    slave_linux_user_group: "{{ agent_user }}"
```

##### EXPECTED RESULTS

The task would choose the RHEL 8 version of the selinux python module and install it.

##### ACTUAL RESULTS

The task chooses the RHEL 7 version of the selinux python module.

```
FAILED! => {"attempts": 10, "changed": false, "failures": ["libselinux-python All matches were filtered out by modular filtering for argument: libselinux-python"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```
